### ISSUE TITLE
训练结果和pytorch有差别吗

### ISSUE THREAD

**Issue by dlml** [saicoco/Gluon-PSENet#1]
已经修复bug, 需要做进一步测评

**Comment by dlml** [comment]
能加一下qq吗

**Comment by saicoco** [comment]
有差距，在kernel分割那里存在一些问题：

- kernel的预测存在问题，根据结果可视化看到的是1，2，5通道的kernel正常，剩下的预测错误；
- 标签校对过，没有问题。

最近没时间debug'这部分，所以遗留了
